name: Metrics
on:
  # Schedule daily updates
  schedule: [{cron: "0 0 * * *"}]
  # (optional) Run workflow manually
  workflow_dispatch:
  # (optional) Run workflow when pushing on master/main
  push: {branches: ["master", "main"]}
jobs:
  github-metrics:
    runs-on: ubuntu-latest
    environment: 
      name: production
    permissions:
      contents: write
    steps:
      - uses: lowlighter/metrics@latest
        with:
          token: ${{ secrets.METRICS_TOKEN }}

          user: phibee
          template: classic
          base: header, activity, repositories
          config_timezone: Europe/Amsterdam
          # Recent Languages
          plugin_languages: yes
          plugin_languages_sections: recently-used
          plugin_languages_recent_load: 400
          plugin_languages_recent_days: 14

          # Wakatime
          # plugin_wakatime: yes
          # plugin_wakatime_sections: time, projects, languages, editors, os
          # plugin_wakatime_token: ${{ secrets.WAKA_KEY }}
          # plugin_wakatime_user: PhiBee

          # Spotify
          plugin_music: yes
          plugin_music_provider: spotify
          plugin_music_mode: recent
          plugin_music_token: ${{ secrets.SPOTIFY_REFRESH_TOKEN }}
          plugin_music_limit: 2
