name: Metrics
on:
  # Schedule daily updates
  schedule: [{cron: "0 0 * * *"}]
  # (optional) Run workflow manually
  workflow_dispatch:
  # (optional) Run workflow when pushing on master/main
  push: {branches: ["master", "main"]}
jobs:
  github-metrics:
    runs-on: ubuntu-latest
    environment: 
      name: production
    permissions:
      contents: write
    steps:
      - uses: lowlighter/metrics@latest
        with:
          token: ${{ secrets.METRICS_TOKEN }}

          user: PhiBeee
          template: classic
          base: header, activity, repositories
          config_timezone: Europe/Amsterdam
          # Recent Languages
          plugin_languages: yes
          plugin_languages_sections: recently-used
          plugin_languages_analysis_timeout: 15
          plugin_languages_categories: markup, programming
          plugin_languages_colors: github
          plugin_languages_limit: 8
          plugin_languages_threshold: 0%
          plugin_languages_indepth: true

          # Wakatime
          plugin_wakatime: yes
          plugin_wakatime_sections: time, projects, languages, languages-graphs, editors, os
          plugin_wakatime_token: ${{ secrets.WAKA_KEY }}
          plugin_wakatime_user: PhiBee

          # Music
          plugin_music: yes
          plugin_music_token: ${{ secrets.LASTFM_TOKEN }}
          plugin_music_provider: lastfm
          plugin_music_user: RJ
